<?php

$mapping = array(
    'Kingdarkness\Goship\Lib\Guzzle\Client' => __DIR__ . '/GuzzleHttp/Client.php',
    'Kingdarkness\Goship\Lib\Guzzle\ClientInterface' => __DIR__ . '/GuzzleHttp/ClientInterface.php',
    'Kingdarkness\Goship\Lib\Guzzle\Cookie\CookieJar' => __DIR__ . '/GuzzleHttp/Cookie/CookieJar.php',
    'Kingdarkness\Goship\Lib\Guzzle\Cookie\CookieJarInterface' => __DIR__ . '/GuzzleHttp/Cookie/CookieJarInterface.php',
    'Kingdarkness\Goship\Lib\Guzzle\Cookie\FileCookieJar' => __DIR__ . '/GuzzleHttp/Cookie/FileCookieJar.php',
    'Kingdarkness\Goship\Lib\Guzzle\Cookie\SessionCookieJar' => __DIR__ . '/GuzzleHttp/Cookie/SessionCookieJar.php',
    'Kingdarkness\Goship\Lib\Guzzle\Cookie\SetCookie' => __DIR__ . '/GuzzleHttp/Cookie/SetCookie.php',
    'Kingdarkness\Goship\Lib\Guzzle\Exception\BadResponseException' => __DIR__ . '/GuzzleHttp/Exception/BadResponseException.php',
    'Kingdarkness\Goship\Lib\Guzzle\Exception\ClientException' => __DIR__ . '/GuzzleHttp/Exception/ClientException.php',
    'Kingdarkness\Goship\Lib\Guzzle\Exception\ConnectException' => __DIR__ . '/GuzzleHttp/Exception/ConnectException.php',
    'Kingdarkness\Goship\Lib\Guzzle\Exception\GuzzleException' => __DIR__ . '/GuzzleHttp/Exception/GuzzleException.php',
    'Kingdarkness\Goship\Lib\Guzzle\Exception\RequestException' => __DIR__ . '/GuzzleHttp/Exception/RequestException.php',
    'Kingdarkness\Goship\Lib\Guzzle\Exception\SeekException' => __DIR__ . '/GuzzleHttp/Exception/SeekException.php',
    'Kingdarkness\Goship\Lib\Guzzle\Exception\ServerException' => __DIR__ . '/GuzzleHttp/Exception/ServerException.php',
    'Kingdarkness\Goship\Lib\Guzzle\Exception\TooManyRedirectsException' => __DIR__ . '/GuzzleHttp/Exception/TooManyRedirectsException.php',
    'Kingdarkness\Goship\Lib\Guzzle\Exception\TransferException' => __DIR__ . '/GuzzleHttp/Exception/TransferException.php',
    'Kingdarkness\Goship\Lib\Guzzle\Handler\CurlFactory' => __DIR__ . '/GuzzleHttp/Handler/CurlFactory.php',
    'Kingdarkness\Goship\Lib\Guzzle\Handler\CurlFactoryInterface' => __DIR__ . '/GuzzleHttp/Handler/CurlFactoryInterface.php',
    'Kingdarkness\Goship\Lib\Guzzle\Handler\CurlHandler' => __DIR__ . '/GuzzleHttp/Handler/CurlHandler.php',
    'Kingdarkness\Goship\Lib\Guzzle\Handler\CurlMultiHandler' => __DIR__ . '/GuzzleHttp/Handler/CurlMultiHandler.php',
    'Kingdarkness\Goship\Lib\Guzzle\Handler\EasyHandle' => __DIR__ . '/GuzzleHttp/Handler/EasyHandle.php',
    'Kingdarkness\Goship\Lib\Guzzle\Handler\MockHandler' => __DIR__ . '/GuzzleHttp/Handler/MockHandler.php',
    'Kingdarkness\Goship\Lib\Guzzle\Handler\Proxy' => __DIR__ . '/GuzzleHttp/Handler/Proxy.php',
    'Kingdarkness\Goship\Lib\Guzzle\Handler\StreamHandler' => __DIR__ . '/GuzzleHttp/Handler/StreamHandler.php',
    'Kingdarkness\Goship\Lib\Guzzle\HandlerStack' => __DIR__ . '/GuzzleHttp/HandlerStack.php',
    'Kingdarkness\Goship\Lib\Guzzle\MessageFormatter' => __DIR__ . '/GuzzleHttp/MessageFormatter.php',
    'Kingdarkness\Goship\Lib\Guzzle\Middleware' => __DIR__ . '/GuzzleHttp/Middleware.php',
    'Kingdarkness\Goship\Lib\Guzzle\Pool' => __DIR__ . '/GuzzleHttp/Pool.php',
    'Kingdarkness\Goship\Lib\Guzzle\PrepareBodyMiddleware' => __DIR__ . '/GuzzleHttp/PrepareBodyMiddleware.php',
    'Kingdarkness\Goship\Lib\Guzzle\RedirectMiddleware' => __DIR__ . '/GuzzleHttp/RedirectMiddleware.php',
    'Kingdarkness\Goship\Lib\Guzzle\RequestOptions' => __DIR__ . '/GuzzleHttp/RequestOptions.php',
    'Kingdarkness\Goship\Lib\Guzzle\RetryMiddleware' => __DIR__ . '/GuzzleHttp/RetryMiddleware.php',
    'Kingdarkness\Goship\Lib\Guzzle\TransferStats' => __DIR__ . '/GuzzleHttp/TransferStats.php',
    'Kingdarkness\Goship\Lib\Guzzle\UriTemplate' => __DIR__ . '/GuzzleHttp/UriTemplate.php',
    'Kingdarkness\Goship\Lib\Guzzle\functions' => __DIR__ . '/GuzzleHttp/functions.php',
    'Kingdarkness\Goship\Lib\Guzzle\functions_include' => __DIR__ . '/GuzzleHttp/functions_include.php',
    'Kingdarkness\Goship\Lib\Guzzle\Promise\AggregateException' => __DIR__ . '/GuzzleHttp/Promise/AggregateException.php',
    'Kingdarkness\Goship\Lib\Guzzle\Promise\CancellationException' => __DIR__ . '/GuzzleHttp/Promise/CancellationException.php',
    'Kingdarkness\Goship\Lib\Guzzle\Promise\Coroutine' => __DIR__ . '/GuzzleHttp/Promise/Coroutine.php',
    'Kingdarkness\Goship\Lib\Guzzle\Promise\EachPromise' => __DIR__ . '/GuzzleHttp/Promise/EachPromise.php',
    'Kingdarkness\Goship\Lib\Guzzle\Promise\FulfilledPromise' => __DIR__ . '/GuzzleHttp/Promise/FulfilledPromise.php',
    'Kingdarkness\Goship\Lib\Guzzle\Promise\Promise' => __DIR__ . '/GuzzleHttp/Promise/Promise.php',
    'Kingdarkness\Goship\Lib\Guzzle\Promise\PromiseInterface' => __DIR__ . '/GuzzleHttp/Promise/PromiseInterface.php',
    'Kingdarkness\Goship\Lib\Guzzle\Promise\PromisorInterface' => __DIR__ . '/GuzzleHttp/Promise/PromisorInterface.php',
    'Kingdarkness\Goship\Lib\Guzzle\Promise\RejectedPromise' => __DIR__ . '/GuzzleHttp/Promise/RejectedPromise.php',
    'Kingdarkness\Goship\Lib\Guzzle\Promise\RejectionException' => __DIR__ . '/GuzzleHttp/Promise/RejectionException.php',
    'Kingdarkness\Goship\Lib\Guzzle\Promise\TaskQueue' => __DIR__ . '/GuzzleHttp/Promise/TaskQueue.php',
    'Kingdarkness\Goship\Lib\Guzzle\Promise\TaskQueueInterface' => __DIR__ . '/GuzzleHttp/Promise/TaskQueueInterface.php',
    'Kingdarkness\Goship\Lib\Guzzle\Promise\functions' => __DIR__ . '/GuzzleHttp/Promise/functions.php',
    'Kingdarkness\Goship\Lib\Guzzle\Promise\functions_include' => __DIR__ . '/GuzzleHttp/Promise/functions_include.php',
    'Kingdarkness\Goship\Lib\Guzzle\Psr7\AppendStream' => __DIR__ . '/GuzzleHttp/Psr7/AppendStream.php',
    'Kingdarkness\Goship\Lib\Guzzle\Psr7\BufferStream' => __DIR__ . '/GuzzleHttp/Psr7/BufferStream.php',
    'Kingdarkness\Goship\Lib\Guzzle\Psr7\CachingStream' => __DIR__ . '/GuzzleHttp/Psr7/CachingStream.php',
    'Kingdarkness\Goship\Lib\Guzzle\Psr7\DroppingStream' => __DIR__ . '/GuzzleHttp/Psr7/DroppingStream.php',
    'Kingdarkness\Goship\Lib\Guzzle\Psr7\FnStream' => __DIR__ . '/GuzzleHttp/Psr7/FnStream.php',
    'Kingdarkness\Goship\Lib\Guzzle\Psr7\InflateStream' => __DIR__ . '/GuzzleHttp/Psr7/InflateStream.php',
    'Kingdarkness\Goship\Lib\Guzzle\Psr7\LazyOpenStream' => __DIR__ . '/GuzzleHttp/Psr7/LazyOpenStream.php',
    'Kingdarkness\Goship\Lib\Guzzle\Psr7\LimitStream' => __DIR__ . '/GuzzleHttp/Psr7/LimitStream.php',
    'Kingdarkness\Goship\Lib\Guzzle\Psr7\MessageTrait' => __DIR__ . '/GuzzleHttp/Psr7/MessageTrait.php',
    'Kingdarkness\Goship\Lib\Guzzle\Psr7\MultipartStream' => __DIR__ . '/GuzzleHttp/Psr7/MultipartStream.php',
    'Kingdarkness\Goship\Lib\Guzzle\Psr7\NoSeekStream' => __DIR__ . '/GuzzleHttp/Psr7/NoSeekStream.php',
    'Kingdarkness\Goship\Lib\Guzzle\Psr7\PumpStream' => __DIR__ . '/GuzzleHttp/Psr7/PumpStream.php',
    'Kingdarkness\Goship\Lib\Guzzle\Psr7\Request' => __DIR__ . '/GuzzleHttp/Psr7/Request.php',
    'Kingdarkness\Goship\Lib\Guzzle\Psr7\Response' => __DIR__ . '/GuzzleHttp/Psr7/Response.php',
    'Kingdarkness\Goship\Lib\Guzzle\Psr7\ServerRequest' => __DIR__ . '/GuzzleHttp/Psr7/ServerRequest.php',
    'Kingdarkness\Goship\Lib\Guzzle\Psr7\Stream' => __DIR__ . '/GuzzleHttp/Psr7/Stream.php',
    'Kingdarkness\Goship\Lib\Guzzle\Psr7\StreamDecoratorTrait' => __DIR__ . '/GuzzleHttp/Psr7/StreamDecoratorTrait.php',
    'Kingdarkness\Goship\Lib\Guzzle\Psr7\StreamWrapper' => __DIR__ . '/GuzzleHttp/Psr7/StreamWrapper.php',
    'Kingdarkness\Goship\Lib\Guzzle\Psr7\UploadedFile' => __DIR__ . '/GuzzleHttp/Psr7/UploadedFile.php',
    'Kingdarkness\Goship\Lib\Guzzle\Psr7\Uri' => __DIR__ . '/GuzzleHttp/Psr7/Uri.php',
    'Kingdarkness\Goship\Lib\Guzzle\Psr7\UriNormalizer' => __DIR__ . '/GuzzleHttp/Psr7/UriNormalizer.php',
    'Kingdarkness\Goship\Lib\Guzzle\Psr7\UriResolver' => __DIR__ . '/GuzzleHttp/Psr7/UriResolver.php',
    'Kingdarkness\Goship\Lib\Guzzle\Psr7\functions' => __DIR__ . '/GuzzleHttp/Psr7/functions.php',
    'Kingdarkness\Goship\Lib\Guzzle\Psr7\functions_include' => __DIR__ . '/GuzzleHttp/Psr7/functions_include.php',
    'Kingdarkness\Goship\Lib\Psr\Message\MessageInterface' => __DIR__ . '/Psr/Http/Message/MessageInterface.php',
    'Kingdarkness\Goship\Lib\Psr\Message\RequestInterface' => __DIR__ . '/Psr/Http/Message/RequestInterface.php',
    'Kingdarkness\Goship\Lib\Psr\Message\ResponseInterface' => __DIR__ . '/Psr/Http/Message/ResponseInterface.php',
    'Kingdarkness\Goship\Lib\Psr\Message\ServerRequestInterface' => __DIR__ . '/Psr/Http/Message/ServerRequestInterface.php',
    'Kingdarkness\Goship\Lib\Psr\Message\StreamInterface' => __DIR__ . '/Psr/Http/Message/StreamInterface.php',
    'Kingdarkness\Goship\Lib\Psr\Message\UploadedFileInterface' => __DIR__ . '/Psr/Http/Message/UploadedFileInterface.php',
    'Kingdarkness\Goship\Lib\Psr\Message\UriInterface' => __DIR__ . '/Psr/Http/Message/UriInterface.php',
);

spl_autoload_register(function ($class) use ($mapping) {
    if (isset($mapping[$class])) {
        require $mapping[$class];
    }
}, true);

require __DIR__ . '/GuzzleHttp/functions.php';
require __DIR__ . '/GuzzleHttp/Psr7/functions.php';
require __DIR__ . '/GuzzleHttp/Promise/functions.php';
